-- Add Ad Budget columns to quotations and invoices tables

ALTER TABLE quotations 
ADD COLUMN IF NOT EXISTS ad_budget NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS ad_budget_pct NUMERIC DEFAULT 15,
ADD COLUMN IF NOT EXISTS ad_budget_fixed NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS ad_budget_override BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS ad_budget_bill_through BOOLEAN DEFAULT FALSE;

ALTER TABLE invoices 
ADD COLUMN IF NOT EXISTS ad_budget NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS ad_budget_pct NUMERIC DEFAULT 15,
ADD COLUMN IF NOT EXISTS ad_budget_fixed NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS ad_budget_override BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS ad_budget_bill_through BOOLEAN DEFAULT FALSE;
